### PR TITLE
Fix :TUP-21173 Make compilation test with Java 11

### PR DESCRIPTION
**Pull request by kjwang-talend**
Fix :TUP-21173 Make compilation test with Java 11
https://jira.talendforge.org/browse/TUP-21173

### CODE REVIEW

**Comment by sbouchet** [comment]
quick question, why does all manifest have changed to add org.talend.core.runtime bundle without any source code change ?

**Comment by kjwang-talend** [comment]
> quick question, why does all manifest have changed to add org.talend.core.runtime bundle without any source code change ?

Because new modules system reason (From JDK 9), There will have compile errors if I don't add these bundle.

**Comment by sbouchet** [comment]
Another comment, is that you removed only the direct com.sun.* import from source code ( which is great ! )  but there is other places where the com.sun.* packages are used .
like in javajet files, in a string constant and also in a pom.xml.

**Comment by kjwang-talend** [comment]
> Another comment, is that you removed only the direct com.sun.* import from source code ( which is great ! ) but there is other places where the com.sun.* packages are used .
> like in javajet files, in a string constant and also in a pom.xml.

Hi, In this ticket, only to check the compile errors to see how much compile errors (Whether is easy to fix them) , Now there are still many run-time errors, I think we will resolve them later. These pull request are  prepare work for JDK 11.

**Pull request closed without merging**
