### PR TITLE
Update tRESTClient_main.javajet

### PR DESCRIPTION
**Pull request by maciej-zygmunt**
Added support for returning response after DELETE command. Solving  problem with DELETE command.
See: https://stackoverflow.com/questions/30307400/talend-trestclient-returns-empty-response-after-delete

### CODE REVIEW

**Comment by yanbasic** [comment]
@maciej-zygmunt, thanks for your fixing, could you please solve the conflict?

**Comment by maciej-zygmunt** [comment]
@yanbasic Mike I am afraid I don't have write access  to merge pull request.

**Comment by yanbasic** [comment]
Hi @maciej-zygmunt , I've solved the conflicts, seems you need to create Pull request again, then I will merge it.

Thanks,
Mike

**Comment by maciej-zygmunt** [comment]
Hi @yanbasic, if this is merged I m closing pull request. Thanks.

**Comment by yanbasic** [comment]
@maciej-zygmunt Thanks for your fix! I merged it.

Regards,
Mike

**Pull request merged**
